title: Jekyll - maxswjeon
description: A Jekyll theme for easy editing experience
url: https://swjeon.dev

plugins:
  - jekyll-postcss
  - jekyll-seo-tag

postcss:
  cache: false

front_matter:
  collections:
    - notes
  remove_originals: true

collections:
  notes:
    output: true
  tabs:
    output: true

defaults:
  - scope:
      path: ""
      type: notes
    values:
      layout: post
      permalink: /posts/:slug/
  - scope:
      path: ""
      type: tabs
    values:
      layout: tab
      permalink: /:title/
