name: Jekyll - Maxswjeon
description: A Jekyll theme for easy editing experience

plugins:
  - jekyll-postcss

postcss:
  cache: false

front_matter:
  collections:
    - notes
  remove_originals: true

collections:
  notes:
    output: true

defaults:
  - scope:
      path: ""
      type: notes
    values:
      layout: post
      permalink: /posts/:slug/index.html
